### ISSUE TITLE
Module not found (problem with GoogleAssistant MagicMirror)

### ISSUE THREAD

**Issue by mnooijen** [bugsounet/MMM-Snowboy#11]
Hello,

I hope someone can help me with this problem. I have installed the 2 modules for my smart mirror and that is MMM-Snowboy and Google Assistant. At first start everything worked properly but got a message that I had to update the Google Assistant and I did. After this I restarted my smart mirror. Now my mirror does not come on and I get a green message in my terminal with the following message that the module "snowboy" is not found. Anyone an idea how to fix this? See my screenshot link so you can see the notification I see. My screenshot link: https://paste.pics/A5S87

Regards,

Marcel

**Comment by bugsounet** [comment]
Hi,
It's not related to MMM-Snowboy and you can't use MMM-Snowboy and MMM-GoogleAssistant at the same time

**Comment by mnooijen** [comment]
Hi,
Ok I have removed the module Snowboy from my script and it now only contains the module of GoogleAssistant. But still I get the error message in my terminal and MagicMirror does not start properly I get a black screen. Can you explain to me how to get this working?

**Comment by mnooijen** [comment]
Hi,

 

Ok I have removed the module Snowboy from my script and it now only contains the module of GoogleAssistant. But still I get the error message in my terminal and MagicMirror does not start properly I get a black screen. Can you explain to me how to get this working?

 

Regards,

 

Marcel Nooijen

 

Van: Cédric <notifications@github.com> 
Verzonden: vrijdag 18 september 2020 23:14
Aan: bugsounet/MMM-Snowboy <MMM-Snowboy@noreply.github.com>
CC: mnooijen <mnooijen@ziggo.nl>; Author <author@noreply.github.com>
Onderwerp: Re: [bugsounet/MMM-Snowboy] Module not found (problem with GoogleAssistant MagicMirror) (#11)

 

Closed #11 <https://github.com/bugsounet/MMM-Snowboy/issues/11> .
