### ISSUE TITLE
Problems with all versions of MMM-Snowboy and MMM-Hotword

### ISSUE THREAD

**Issue by SikandAlex** [bugsounet/MMM-Snowboy#7]
I've spent the last 10 hours non-stop trying to get MMM-Snowboy or MMM-Hotword to work on my Mac OSX computer running Catalina. 

## First Try
https://github.com/Zuyderwijk/MMM-Snowboy

I used this version of the library and just changed `record.start` to `record.record` to fix compatibility issues with the latest version of node-record-lpcm-16. 

It successfully detects the hotword and triggers MMM-AssistantMk2 but the server always redirects to the Google authentication prompt (even though I have the token.json and credential.json properly configured). 

## Second Try
https://github.com/bugsounet/MMM-Snowboy/

After only a few seconds, Snowboy will stop listening because of problems with 16K sampling. Even if you manage to speak the hotword and activate Assistant before Snowboy decides to stop listening, the Google Assistant will just keep spinning and spinning and will never reset to it's normal state.

New Macbooks only have 44,100 Hz 48,000 Hz 88,200 Hz and 96,000 Hz sampling format for the coreaudio device. 

Even if you use `{recorder: 'rec', device: null}`, rec will throw errors about being unable to set the sample rate so you need to use `node-record-lpcm-16` (which works fine) instead of the custom `lpcm16.js` class in the components folder. I tried to edit the lpcm16.js file to use `node-record-lpcm-16` instead but it doesn't help because for some reason I can't find any external files that reference this node module. The only mention of the LPCM16 class is in lpcm16.js: https://github.com/bugsounet/MMM-Snowboy/search?q=lpcm16&unscoped_q=lpcm16

And it's never referenced from anywhere else so I don't know how to fix this. 

## Third Try 
https://github.com/bugsounet/MMM-Hotword/

Same issues as the second try, with the additional problem that even when the hotword is detected, MMM-AssistantMk2 is NEVER activated. I've tested this with MANY different configurations discussed in other issues and forums. 

I'm sure that this library works better on an RPi but I do not have an external monitor and RPi available right now and I want to contribute to this repository after testing my code on my Mac. 

I really don't know why this is so difficult to setup.

**Comment by bugsounet** [comment]
> First Try

i don't use `node-record-lpcm-16` (too much problem with RPI) and i don't use original `snowboy`
I use my own npm build since v1.1.0

>> the server always redirects to the Google authentication prompt
you don't set the default profile correctly

> Second Try:
it's APi of snowboy detect
MMM-Hotword have been developed with Mac
I have no Mac for testing

> Third Try
>> Same issues as the second try, with the additional problem that even when the hotword is detected, MMM-AssistantMk2 is NEVER activated.
if detected and never activated ... means MMM-Hotword is not prepared for AMk2 (recipes)
and for MMM-AssistantMk2 need to be prepared for MMM-Hotword (recipes too)
AMk2 Wiki can help you

**Comment by SikandAlex** [comment]
Ok honestly just go ahead and close this issue. I just ordered a Raspberry Pi. I wanted to develop a fork of some of your code but it's just silly trying to build it on a Mac when the production target is a RPi.
